spring:
  application:
    name: deal
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: neoflex
    password: neoflex
  data:
    jdbc:
      dialect: postgresql
  liquibase:
    change-log: db/changelog/init-changelog.xml
server:
  port: 8081
service:
  calculator:
    url: http://localhost:8080/calculator
    path:
      offers: /offers
      calculate: /calc