spring:
  application:
    name: deal
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${DB_USERNAME:neoflex}
    password: ${DB_PASSWORD:neoflex}
  data:
    jdbc:
      dialect: postgresql
  liquibase:
    change-log: db/changelog/init-changelog.xml
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .txt
    mode: TEXT
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:pass}
server:
  port: 8081
service:
  calculator:
    url: ${CALCULATOR_URL:http://localhost:8080/calculator}
    path:
      offers: /offers
      calculate: /calc
messaging:
  topics:
    - name: finish-registration
      partitions: 1
      replicas: 1
    - name: create-documents
      partitions: 1
      replicas: 1
    - name: send-documents
      partitions: 1
      replicas: 1
    - name: send-ses
      partitions: 1
      replicas: 1
    - name: credit-issued
      partitions: 1
      replicas: 1
    - name: statement-denied
      partitions: 1
      replicas: 1
