spring:
  application:
    name: deal
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: neoflex
    password: neoflex
server:
  port: 8081

service:
  calculator:
    url: http://localhost:8080/calculator