spring:
  application:
    name: statement
server:
  port: 8082
service:
  deal:
    url: ${DEAL_URL:http://localhost:8081/deal}
    path:
      statement: /statement
      select-offer: /offer/select
wiremock:
  server:
    baseUrl: http://localhost:8081/deal
