spring:
  application:
    name: gateway
service:
  calculator:
    url: ${CALCULATOR_URL:http://localhost:8080/calculator}
    path:
      offers: /offers
      calculate: /calc
  deal:
    url: ${DEAL_URL:http://localhost:8081/deal}
    path:
      statement: /statement
      select-offer: /offer/select
      calculate: /calculate/{statementId}
      send-documents: /document/{statementId}/send
      send-ses-code: /document/{statementId}/code
      sign-documents: /document/{statementId}/sign
  statement:
    url: ${STATEMENT_URL:http://localhost:8082/statement}
    path:
      statement:
      select-offer: /offer
server:
  port: 8888



