spring:
  application:
    name: gateway
service:
  calculator:
    url: http://localhost:8080/calculator
    path:
      offers: /offers
      calculate: /calc
  deal:
    url: http://localhost:8081/deal
    path:
      statement: /statement
      select-offer: /offer/select
      calculate: /calculate/{statementId}
      send-documents: /document/{statementId}/send
      send-ses-code: /document/{statementId}/code
      sign-documents: /document/{statementId}/sign
  statement:
    url: http://localhost:8082/statement
    path:
      statement:
      select-offer: /offer
server:
  port: 8888



