spring:
  application:
    name: dossier
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: dossier-group
      properties:
        spring:
          deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: "neoflex.deal.messaging.dto"
            value:
              default:
                type: "neoflex.dossier.messaging.dto.EmailMessageDto"
  mail:
    host: smtp.mail.ru
    port: 587
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8083

messaging:
  topics:
    - name: finish-registration
      partitions: 1
      replicas: 1
    - name: create-documents
      partitions: 1
      replicas: 1
    - name: send-documents
      partitions: 1
      replicas: 1
    - name: send-ses
      partitions: 1
      replicas: 1
    - name: credit-issued
      partitions: 1
      replicas: 1
    - name: statement-denied
      partitions: 1
      replicas: 1