name: Build and deploy "Bank with Love" project
on:
  push:
    branches:
      - main
      - develop
      - deploy
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'corretto'
            architecture: x64
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: Run tests
        run: mvn clean test
      - name: Build Maven projects
        run: mvn clean package -DskipTests
      - name: Upload entire project as artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-build
          path: |
            .
            !.git
            !.github
          retention-days: 1

  deploy:
    runs-on: self-hosted
    needs: build-and-test
    steps:
      - name: Clean workspace
        run: rm -rf rm -rf ${{ github.workspace }}/*

      - name: Download project artifact
        uses: actions/download-artifact@v4
        with:
          name: project-build
          path: ${{ github.workspace }}

      - name: Make scripts executable
        run: |
          find ${{ github.workspace }} -name "*.sh" -exec chmod +x {} \;
          ls -la

      - name: Build Docker images
        run: docker compose build

      - name: Deploy with Docker Compose
        run: |
          docker compose down || true
          docker compose up -d
          sleep 30
          docker-compose ps